parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

redis:
    clients:
        teapot:
            host: "localhost"
            port: 6379
            database: "0"
            protocol: "redis://"
            idle: 0.5
            timeout: 3.0

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    
    App\Teapot\:
        resource: '%app_path%/src/Teapot/*'
        exclude: '%app_path%/src/Teapot/{Command,Exception,View}'

    App\Infrastructure\:
        resource: '%app_path%/src/Infrastructure/*'
        exclude: '%app_path%/src/Infrastructure/{Type,Migrations}'
    
    App\Infrastructure\Controller\:
        resource : "%app_path%/src/Infrastructure/Controller/*"
        tags:
            - {name: controller.service_arguments}  
        
    App\Infrastructure\Repository\TeapotRepository:
        class: App\Infrastructure\Repository\TeapotRepository
        arguments:
            - "@redis.teapot_client"

    Violines\RestBundle\Negotiation\ContentNegotiator:
        alias: violines_rest.negotiation.content_negotiator

    Violines\RestBundle\Response\ResponseBuilder:
        alias: violines_rest.response.response_builder

    Violines\RestBundle\Serialize\Serializer:
        alias: violines_rest.serialize.serializer